name: medical_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  lottie: ^1.2.2
  carousel_slider: ^4.0.0
  flutter_speed_dial: ^5.0.0+1
  ml_kit_image_labeler: ^0.0.3+2
  google_maps_flutter: ^2.1.8
  google_maps_controller: ^1.2.0
  geolocator: ^8.0.1
  flutter_polyline_points: ^1.0.0
  circular_menu: ^2.0.0
  pandabar: ^0.1.2

  





  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+11
  ml_kit_ocr: ^0.0.3+1
  flutter_neat_and_clean_calendar: ^0.3.6+19
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/lottiefile/
  